# permissions for end users to view houmaoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: houmao-viewer-role
rules:
- apiGroups:
  - sunwukong.my.domain
  resources:
  - houmaoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sunwukong.my.domain
  resources:
  - houmaoes/status
  verbs:
  - get
